language: python
python:
- 3.6
sudo: required
services:
- docker
script:
- bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST = "false"
env:
  global:
  - secure: GqprHNniCN0bmqPJzShKvkKuBSc5eUUV2EY6PvqCvMorJK20SBvCEO3NGBWDC8ABM7l7ZdYPe/PY3JENNTrT+BI51ZsLSEETP7zGVsOlIyuWQgl2qAmwh2JZABTLCh2i76bq+CUAiGrzJwWgwo2XtuzFKbosD5LkwxJsyxkgZ7a0WUkZm1VFT4wRpXoDM8rbVhNkiv9ntejb6iF8ITrfFReEdlhwohBNnQ0JO1oA/R0neHmP4j39gwWZ6xDPN6K0ShATwJGjPzgeYQ6mBNFsfZekgqNQSUFqxkBbdUOiOtg9IoCfj/5nViMsV/aIbkUTj+j833Nu63XJk4RrWdyz6CB0KZO8iiIs6arkDfvm4ml/waoaNi1+dCdCj+0W1gM1hmqSb8PBSFZMI7lbqahzlfIu2H5bmIJKyxYpIIu0EIo8F4XcQXz4lG/selU/J3u1nomE9OEqTdEjxaw6Sta5ZYRLC61Kwt5G+WUFkhadx/Byk1VJA5O3iWd+eYxvR6pqw3USK6DPOhMy9/HY65EWHsyanJcxqrdnNRa/1Ip2fWjfMO8RdPOdGpGJHlXAii00L7dUtmw8R+aC65oLuYjIbRlp/FwXu/TkBcln9Z3q45RONHZgmeVQLubYh0s+PrFXyb8QHWsKfZ7u/czAUbhQ5Q4U8brTwvdFJZ3D6co4sh8=
  - secure: jlkfERP3yW3aSceYcUN8sHuyyRPceNo4YtknIc9hNyFtdSmlkECcJFm5JcTan1Q+6BjCziMgWAL29h5yFLF0PsqQK4QMjde1Rzlndi66fK5Z5cDsIhZ0MiebXyx1h4Q6G+UWRcz4mEVmvrHQ2txMNbgd8JbRIPbvXDCmD1yo6WJYmjYYPXqNXTSKTrCSJGCVgfOD87ZqDYYLoHO4Tsy9Ml/llBKOuMMWun1Q7x+1PEKiLHQU9TY9MWTy2tCpUM0Ds+yMLVrUgqREsvNz60fM7QwgXNJb9MmdoqPpFJqQTGECmXiVq/gTTgBuJBlw2L5uLRXT43fvRMP2cTUWJZpqLRfLt0fZQaG6K3bSSqoIV2tNWoQOGv6wtsrd68BkCBDQrxPAg8jZA5UUd2v2DL2zx3UFJ3uns0x2o3gDN3I4vgRkeJMjihGIqxfwHQ0bJBqz5OSlGhzJOQU+Jn6XqonTKJtwgg1NiRkakPSP4MuwKZUaYb3+/GHuNnbhEqM8u7yyA0N0W8rIWFQcEnWpKnd5xpd1muhGsKq9RmfakRvO9q2lwpkjoHUNDLFb1ufM81J8FEtUB8knyjRobQRxELGuCfjsK9i/X6kB/svarSiqAqD5F0FiipW/ZD5pUlxdv+7sqgZwWndhEgzOnVBoSbvNb94ZzKpg1OSh0oXXmJtzx2Y=
